#!/bin/bash

LOCAL_SOURCE_DIR=/tmp/src
pushd $LOCAL_SOURCE_DIR

if [ -a /tmp/kakadu/make/Makefile-Linux-x86-64-gcc ]; then
 pushd /tmp/kakadu/make
 make -f Makefile-Linux-x86-64-gcc all
 popd
 ./autogen.sh && ./configure --with-kakadu=/tmp/kakadu && make
 cp -r /tmp/kakadu/lib/Linux-x86-64-gcc/* /usr/local/lib/
else
  git clone https://github.com/uclouvain/openjpeg.git
  pushd openjpeg
  cmake .
  make install
  popd
  ./autogen.sh && ./configure --with-openjpeg=/tmp/src/openjpeg && make
fi
