version: '3'
services:
  solr:
    image: moravianlibrary/solr:8.0.0-dnnt
    container_name: solr_kramerius
    environment:
      - SOLR_TIMEZONE=Europe/Prague
    ports:
      - 8983:8983
    restart: always
