fcrepo:
  build: .
  volumes:
    - /data/fcrepo/datastreams:/usr/local/fedora/data/datastreams
    - /data/fcrepo/objects:/usr/local/fedora/data/objects
    - /data/fcrepo/resourceIndex:/usr/local/fedora/data/resourceIndex
  environment:
    - FEDORA_PASSWORD=fedoraAdmin
  ports:
    - "8080"
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
  volumes:
    - /data/fcrepo/fedorapostgres:/var/lib/postgresql/data
riTriplesPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
  volumes:
    - /data/fcrepo/ritriplespostgres:/var/lib/postgresql/data
