fcrepo:
  build: .
  volumes:
    - /data/fcrepo:/usr/local/fedora/data
  ports:
    - "8080:8080"
  environment:
    - FEDORA_PASSWORD=fedoraAdmin
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
  volumes:
    - /data/fcrepo/fedorapostgres:/var/lib/postgresql/data
riTriplesPostgres:
  image: "martinrumanek/postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
  volumes:
    - /data/fcrepo/ritriplespostgres:/var/lib/postgresql/data
